### PR TITLE
Fix problem of checkboxes not showing up

### PR DESCRIPTION
**Pull request by eschan145**

### CODE REVIEW

**Comment by hkzorman** [comment]
Thank you for your contribution! 👍

**Comment by eschan145** [comment]
I discovered this just yesterday and have seen how much work has already been put in to this framework. However there is almost no activity here (one star, one fork, one watcher). You probably should put a working example for people to see and try out.

**Comment by hkzorman** [comment]
Thank you. Once I have completed the items for the alpha version (as per this very same roadmap document you helped me fix the markdown for), I will post it in the Minetest forums, along with a sample NPC. I want to make sure that what I release is usable and stable enough before doing so.

In the meantime, your contributions and anyone's else are most welcome!

**Comment by eschan145** [comment]
I would suggest you make separate modpacks once the mod is completely finished. This way, people have a lot of options on what and what not to install. I noticed in `advanced_npc` that the NPCs are mostly villager-like. An NPC can also be a guard or a human-like monster.

* `apnc_villagers` would create initialize and spawn villagers automatically in `mg_villages`, such as in `advanced_npc`.
* `anpc_monsters` would create npc-like mobs that would attack and plunder villages
* `anpc_guards` would be player-created guards that would help defend and protect the village

**Pull request merged**
